name: mousenet

channels:
  - pytorch
  - conda-forge

dependencies:
  - python=3.8
  - shapely
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pytest
  - flake8
  - networkx
  - network
  - rope
  - autopep8
  - black
  - click
  - jupyter
  - pyyaml
  - pytorch>=1.1.0
  - torchvision
  - cudatoolkit=10.0
  - tensorboard>=1.14
  - absl-py
  - future
  - tqdm
  - pip
  - pip:
    - -e .  # install package in development mode
    - git+https://github.com/AllenInstitute/mouse_connectivity_models.git
